INSERT INTO trd_catalogo_series (codigo, nombre) VALUES
  ('1',  'ACCIONES CONSTITUCIONALES'),
  ('2',  'ACCIONES JUDICIALES'),
  ('3',  'ACTAS'),
  ('4',  'ACTOS ADMINISTRATIVOS'),
  ('5',  'ACUERDOS'),
  ('6',  'ANTEPROYECTO DE PRESUPUESTO'),
  ('7',  'AUDITORIAS'),
  ('8',  'BOLETINES'),
  ('9',  'CERTIFICADOS'),
  ('10', 'CIRCULARES'),
  ('11', 'COMPROBANTES CONTABLES'),
  ('12', 'COMPROBANTES DE ALMACEN'),
  ('13', 'CONCEPTOS'),
  ('14', 'CONCILIACIONES BANCARIAS'),
  ('15', 'CONSECUTIVO DE COMUNICACIONES'),
  ('16', 'CONTRATOS'),
  ('17', 'CONVENIOS'),
  ('18', 'DERECHOS DE PETICION'),
  ('19', 'DECLARACIONES TRIBUTARIAS'),
  ('20', 'ESTADOS FINANCIEROS'),
  ('21', 'ESTUDIOS'),
  ('22', 'HISTORIALES'),
  ('23', 'HISTORIAS LABORALES'),
  ('24', 'INFORMES'),
  ('25', 'INSTRUMENTOS ARCHIVISTICOS'),
  ('26', 'INSTRUMENTOS DE CONTROL'),
  ('27', 'INVENTARIOS'),
  ('28', 'LIBROS CONTABLES'),
  ('29', 'MANUALES'),
  ('30', 'NOMINA'),
  ('31', 'PLANES'),
  ('32', 'PROGRAMAS'),
  ('33', 'PROCESOS'),
  ('34', 'PROYECTOS'),
  ('35', 'REGISTROS'),
  ('36', 'RESOLUCIONES'),
  ('37', 'PQRS')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO trd_catalogo_subseries (codigo, nombre, serie_id) VALUES
  ('1.1','Acciones de cumplimiento',(SELECT id FROM trd_catalogo_series WHERE codigo='1')),
  ('1.2','Acciones de grupo',       (SELECT id FROM trd_catalogo_series WHERE codigo='1')),
  ('1.3','Acciones de tutela',      (SELECT id FROM trd_catalogo_series WHERE codigo='1')),
  ('1.4','Acciones populares',      (SELECT id FROM trd_catalogo_series WHERE codigo='1')),
  ('2.1','Acciones contractuales',                (SELECT id FROM trd_catalogo_series WHERE codigo='2')),
  ('2.2','Acciones de nulidad',                   (SELECT id FROM trd_catalogo_series WHERE codigo='2')),
  ('2.3','Acciones de nulidad y restablecimiento',(SELECT id FROM trd_catalogo_series WHERE codigo='2')),
  ('2.4','Acciones de reparacion directa',        (SELECT id FROM trd_catalogo_series WHERE codigo='2')),
  ('2.5','Acciones de repeticion',                (SELECT id FROM trd_catalogo_series WHERE codigo='2')),
  ('2.6','Acciones ordinarias',                   (SELECT id FROM trd_catalogo_series WHERE codigo='2')),
  ('3.1','Actas de comites',        (SELECT id FROM trd_catalogo_series WHERE codigo='3')),
  ('3.2','Actas de consejos',       (SELECT id FROM trd_catalogo_series WHERE codigo='3')),
  ('3.3','Actas de comisiones',     (SELECT id FROM trd_catalogo_series WHERE codigo='3')),
  ('3.4','Actas institucionales',   (SELECT id FROM trd_catalogo_series WHERE codigo='3')),
  ('3.5','Actas de juntas',         (SELECT id FROM trd_catalogo_series WHERE codigo='3')),
  ('3.6','Actas de mesas tecnicas', (SELECT id FROM trd_catalogo_series WHERE codigo='3')),
  ('4.1','Decretos',                (SELECT id FROM trd_catalogo_series WHERE codigo='4')),
  ('4.2','Resoluciones',            (SELECT id FROM trd_catalogo_series WHERE codigo='4')),
  ('5.1','Acuerdos municipales',    (SELECT id FROM trd_catalogo_series WHERE codigo='5')),
  ('7.1','Auditorias internas',     (SELECT id FROM trd_catalogo_series WHERE codigo='7')),
  ('7.2','Auditorias externas',     (SELECT id FROM trd_catalogo_series WHERE codigo='7')),
  ('8.1','Boletines administrativos',(SELECT id FROM trd_catalogo_series WHERE codigo='8')),
  ('8.2','Boletines de prensa',      (SELECT id FROM trd_catalogo_series WHERE codigo='8')),
  ('8.3','Boletines epidemiologicos',(SELECT id FROM trd_catalogo_series WHERE codigo='8')),
  ('9.1','Certificados presupuestales',  (SELECT id FROM trd_catalogo_series WHERE codigo='9')),
  ('9.2','Certificados administrativos', (SELECT id FROM trd_catalogo_series WHERE codigo='9')),
  ('9.3','Certificados de residencia',   (SELECT id FROM trd_catalogo_series WHERE codigo='9')),
  ('9.4','Certificados financieros',     (SELECT id FROM trd_catalogo_series WHERE codigo='9')),
  ('10.1','Circulares informativas', (SELECT id FROM trd_catalogo_series WHERE codigo='10')),
  ('10.2','Circulares dispositivas', (SELECT id FROM trd_catalogo_series WHERE codigo='10')),
  ('11.1','Ingreso',(SELECT id FROM trd_catalogo_series WHERE codigo='11')),
  ('11.2','Egreso', (SELECT id FROM trd_catalogo_series WHERE codigo='11')),
  ('12.1','Ingreso',(SELECT id FROM trd_catalogo_series WHERE codigo='12')),
  ('12.2','Egreso', (SELECT id FROM trd_catalogo_series WHERE codigo='12')),
  ('12.3','Baja',   (SELECT id FROM trd_catalogo_series WHERE codigo='12')),
  ('13.1','Conceptos juridicos',(SELECT id FROM trd_catalogo_series WHERE codigo='13')),
  ('13.2','Conceptos tecnicos', (SELECT id FROM trd_catalogo_series WHERE codigo='13')),
  ('15.1','Enviadas', (SELECT id FROM trd_catalogo_series WHERE codigo='15')),
  ('15.2','Recibidas',(SELECT id FROM trd_catalogo_series WHERE codigo='15')),
  ('16.1','Arrendamiento',          (SELECT id FROM trd_catalogo_series WHERE codigo='16')),
  ('16.2','Comodato',               (SELECT id FROM trd_catalogo_series WHERE codigo='16')),
  ('16.3','Compraventa',            (SELECT id FROM trd_catalogo_series WHERE codigo='16')),
  ('16.4','Consultoria',            (SELECT id FROM trd_catalogo_series WHERE codigo='16')),
  ('16.5','Obra publica',           (SELECT id FROM trd_catalogo_series WHERE codigo='16')),
  ('16.6','Prestacion de servicios',(SELECT id FROM trd_catalogo_series WHERE codigo='16')),
  ('16.7','Interadministrativos',   (SELECT id FROM trd_catalogo_series WHERE codigo='16')),
  ('16.8','Seguros',                (SELECT id FROM trd_catalogo_series WHERE codigo='16')),
  ('16.9','Suministros',            (SELECT id FROM trd_catalogo_series WHERE codigo='16')),
  ('17.1','Interadministrativos',(SELECT id FROM trd_catalogo_series WHERE codigo='17')),
  ('17.2','Cooperacion',         (SELECT id FROM trd_catalogo_series WHERE codigo='17')),
  ('17.3','Asociacion',          (SELECT id FROM trd_catalogo_series WHERE codigo='17')),
  ('17.4','ESAL',                (SELECT id FROM trd_catalogo_series WHERE codigo='17')),
  ('19.1','IVA',                    (SELECT id FROM trd_catalogo_series WHERE codigo='19')),
  ('19.2','Retencion',              (SELECT id FROM trd_catalogo_series WHERE codigo='19')),
  ('19.3','Impuestos territoriales',(SELECT id FROM trd_catalogo_series WHERE codigo='19')),
  ('21.1','Estudios tecnicos',         (SELECT id FROM trd_catalogo_series WHERE codigo='21')),
  ('21.2','Estudios organizacionales', (SELECT id FROM trd_catalogo_series WHERE codigo='21')),
  ('21.3','Diseños',                   (SELECT id FROM trd_catalogo_series WHERE codigo='21')),
  ('22.1','Bienes',        (SELECT id FROM trd_catalogo_series WHERE codigo='22')),
  ('22.2','Equipos',       (SELECT id FROM trd_catalogo_series WHERE codigo='22')),
  ('22.3','Vehiculos',     (SELECT id FROM trd_catalogo_series WHERE codigo='22')),
  ('22.4','Educativos',    (SELECT id FROM trd_catalogo_series WHERE codigo='22')),
  ('22.5','Contribuyentes',(SELECT id FROM trd_catalogo_series WHERE codigo='22')),
  ('24.1','Informes de gestion',        (SELECT id FROM trd_catalogo_series WHERE codigo='24')),
  ('24.2','Informes a entes de control',(SELECT id FROM trd_catalogo_series WHERE codigo='24')),
  ('24.3','Informes financieros',       (SELECT id FROM trd_catalogo_series WHERE codigo='24')),
  ('24.4','Informes tecnicos',          (SELECT id FROM trd_catalogo_series WHERE codigo='24')),
  ('24.5','Informes de seguimiento',    (SELECT id FROM trd_catalogo_series WHERE codigo='24')),
  ('24.6','Informes PQRS',             (SELECT id FROM trd_catalogo_series WHERE codigo='24')),
  ('25.1','CCD',   (SELECT id FROM trd_catalogo_series WHERE codigo='25')),
  ('25.2','TRD',   (SELECT id FROM trd_catalogo_series WHERE codigo='25')),
  ('25.3','PGD',   (SELECT id FROM trd_catalogo_series WHERE codigo='25')),
  ('25.4','PINAR', (SELECT id FROM trd_catalogo_series WHERE codigo='25')),
  ('27.1','Documentales',   (SELECT id FROM trd_catalogo_series WHERE codigo='27')),
  ('27.2','Bienes',         (SELECT id FROM trd_catalogo_series WHERE codigo='27')),
  ('27.3','Transferencias', (SELECT id FROM trd_catalogo_series WHERE codigo='27')),
  ('28.1','Libro diario',(SELECT id FROM trd_catalogo_series WHERE codigo='28')),
  ('28.2','Libro mayor', (SELECT id FROM trd_catalogo_series WHERE codigo='28')),
  ('28.3','Libro bancos',(SELECT id FROM trd_catalogo_series WHERE codigo='28')),
  ('31.1','Planes de accion',      (SELECT id FROM trd_catalogo_series WHERE codigo='31')),
  ('31.2','Planes estrategicos',   (SELECT id FROM trd_catalogo_series WHERE codigo='31')),
  ('31.3','Planes institucionales',(SELECT id FROM trd_catalogo_series WHERE codigo='31')),
  ('31.4','Planes de mejoramiento',(SELECT id FROM trd_catalogo_series WHERE codigo='31')),
  ('32.1','Programas institucionales',(SELECT id FROM trd_catalogo_series WHERE codigo='32')),
  ('32.2','Programas sociales',       (SELECT id FROM trd_catalogo_series WHERE codigo='32')),
  ('33.1','Procesos judiciales',     (SELECT id FROM trd_catalogo_series WHERE codigo='33')),
  ('33.2','Procesos disciplinarios', (SELECT id FROM trd_catalogo_series WHERE codigo='33')),
  ('33.3','Procesos administrativos',(SELECT id FROM trd_catalogo_series WHERE codigo='33')),
  ('33.4','Procesos sancionatorios', (SELECT id FROM trd_catalogo_series WHERE codigo='33')),
  ('34.1','Proyectos de acuerdo',    (SELECT id FROM trd_catalogo_series WHERE codigo='34')),
  ('34.2','Proyectos institucionales',(SELECT id FROM trd_catalogo_series WHERE codigo='34')),
  ('35.1','Registro de usuarios',    (SELECT id FROM trd_catalogo_series WHERE codigo='35')),
  ('35.2','Registros administrativos',(SELECT id FROM trd_catalogo_series WHERE codigo='35')),
  ('37.1','Peticiones', (SELECT id FROM trd_catalogo_series WHERE codigo='37')),
  ('37.2','Quejas',     (SELECT id FROM trd_catalogo_series WHERE codigo='37')),
  ('37.3','Reclamos',   (SELECT id FROM trd_catalogo_series WHERE codigo='37')),
  ('37.4','Sugerencias',(SELECT id FROM trd_catalogo_series WHERE codigo='37'))
ON CONFLICT (codigo, serie_id) DO NOTHING;
